import Header from '@/components/header/Header';
import UserProvider from './providers/UserProvider';

export const metadata = {
	title: 'Susende Framover',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<UserProvider>
					<Header />
					{children}
				</UserProvider>
			</body>
		</html>
	);
}
