import { NextAuthProvider } from './providers/NextAuthProvider';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<NextAuthProvider>{children}</NextAuthProvider>
			</body>
		</html>
	);
}
